apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraudguard-app
  namespace: fraudguard
  labels:
    app: fraudguard-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraudguard-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: fraudguard-app
    spec:
      containers:
        - name: fraudguard
          image: kautilyasingh/fraudguard:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: LOG_LEVEL
              value: "INFO"
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.13.0
          securityContext:
            runAsUser: 0
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: app-logs
              mountPath: /var/log/app
              readOnly: true
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: filebeat-config
          configMap:
            name: filebeat-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: fraudguard
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths: [/var/log/app/fraud.log]
        json.keys_under_root: true
        json.add_error_key: true
    output.logstash:
      hosts: ["logstash-service:5044"]
    logging.level: warning
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fraudguard-hpa
  namespace: fraudguard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fraudguard-app
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
