apiVersion: v1
kind: Service
metadata:
  name: fraudguard-service
  namespace: fraudguard
spec:
  type: NodePort
  selector:
    app: fraudguard-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
